### ISSUE TITLE
Error when parsing schematic

### ISSUE THREAD

**Issue by Atm85** [BlockHorizons/libschematic#11]
```
[14:00:54] [Server thread/CRITICAL]: Error: "Class 'pocketmine\nbt\BigEndianNbtSerializer' not found" (EXCEPTION) in "C:/Users/Stephen/Documents/Main/virions/libschematic/src/BlockHorizons/libschematic/Schematic" at line 85
```
running version; _PocketMine-MP 3.9.4 for Minecraft: Bedrock Edition v1.12.0 (protocol version 361)_

code im using..
```php
use BlockHorizons\libschematic\Schematic;

/*----------------------------------------------*/

$schematic = new Schematic();
$schematic->parse($this->getDataFolder().'schematics/house.schematic');

$position = $sender->getPosition();
foreach ($schematic->blocks() as $block) {
    $position->level->setBlock($position->add($block), $block);
}
```

**Comment by Sandertv** [comment]
As the API in the .poggit.yml mentions, this library is written for PocketMine API 4.0.0, which has not yet been released. Please check the open merge request for a 3.0 version.

**Comment by rjworks** [comment]
> As the API in the .poggit.yml mentions, this library is written for PocketMine API 4.0.0, which has not yet been released. Please check the open merge request for a 3.0 version.

can you make api3 branch
