### ISSUE TITLE
Why is this not being built on poggit?

### ISSUE THREAD

**Issue by jasonw4331** [BlockHorizons/libschematic#6]
I see the virion.yml but it doesn't appear to have any available builds on poggit 
![screenshot 4](https://user-images.githubusercontent.com/16521025/50703178-4f2fab00-1021-11e9-91ff-58172953db5c.png)

**Comment by Sandertv** [comment]
Not entirely sure. I'll try re-activating it.

**Comment by Sandertv** [comment]
Should work now
